name: task
description: Task for Pro Grammics

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.0
  firebase_core: ^2.8.0
  firebase_auth: ^4.2.2
  shared_preferences: ^2.0.18
  cloud_firestore: ^4.4.5
  firebase_storage: ^11.0.16
  fluttertoast: ^8.2.2
  firebase_app_check: ^0.1.1+14
  pinput: ^2.2.31
  photo_view: ^0.14.0
  shimmer: ^2.0.0
  provider: ^6.0.5
  lottie: ^2.3.2
  fluro: ^2.0.5
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  equatable: ^2.0.5
  google_fonts: ^3.0.1
  bootstrap_icons: ^1.10.2
  dio: ^5.1.0




  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lotties/
